# Generated by Django 4.1.6 on 2023-02-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riddle',
            options={'verbose_name': 'Riddle', 'verbose_name_plural': 'Riddles'},
        ),
    ]
