# Generated by Django 4.1.7 on 2023-02-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/Django.jpg', upload_to='img'),
        ),
    ]
